name: notube_shared
description: Shared Proto and Data for NoTube
version: 0.0.0-PLACEHOLDER
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^5.0.0

# Expose the JSON file as a Flutter asset
flutter:
  assets:
    - assets/default_alternatives.json